import type { LegalBlock, LegalDocument } from "../content/index.ts";
import { SITE_ORIGIN, canonicalUrl, documentPages, outputFile } from "./site.ts";
import type { DocumentPage } from "./site.ts";

// Renders the whole site as plain static files. A pure presentation layer:
// every legal string comes from content/* verbatim, and no block type can
// inject markup or load anything. The pages carry no scripts, fonts, images,
// analytics or external resources of any kind: the documents state the apps
// have no tracking, and a store reviewer may open them with a plain HTTP
// client that runs no JavaScript.

export const CNAME = "legal.tricktic.com";

const GENERATED_NOTE =
  "<!-- Generated by src/build.ts from content/. Do not edit: run `pnpm build`. -->";

// Ported from automations-website's app-legal.module.css. The pages carry
// their own light and dark palette because a reviewer may open them in either
// scheme. `overflow-wrap` lets long URLs in the text wrap on a phone instead of
// pushing the page sideways.
const STYLE = `:root {
  color-scheme: light dark;

  --background: #06080b;
  --foreground: #eafdf5;
  --heading: #33f2a6;
  --link: #70f7bd;
  --border: #355047;
  --muted: #a8b8b2;

  background: var(--background);
  color: var(--foreground);
  font-family: system-ui, sans-serif;
  height: 100%;
  line-height: 1.6;
}

@media (prefers-color-scheme: light) {
  :root {
    --background: #f5fbf8;
    --foreground: #13231d;
    --heading: #087953;
    --link: #087953;
    --border: #b5ccc3;
    --muted: #52675f;
  }
}

body {
  background: var(--background);
  color: var(--foreground);
  margin: 0;
  min-height: 100%;
}

.document {
  margin: 0 auto;
  max-width: 760px;
  overflow-wrap: break-word;
  padding: 32px 20px 64px;
}

.title {
  color: var(--heading);
  font-size: 2em;
  line-height: 1.2;
  margin: 0 0 0.4em;
}

.updated {
  color: var(--muted);
  margin: 0 0 1.4em;
}

.heading {
  font-size: 1.5em;
  line-height: 1.2;
  margin: 1.6em 0 0.6em;
}

.paragraph {
  margin: 0 0 1em;
}

.link {
  color: var(--link);
}

/* Two text columns can overflow a narrow phone, so the table scrolls inside
   its own box instead of pushing the page sideways. */
.table-scroll {
  overflow-x: auto;
}

.table {
  border-collapse: collapse;
  width: 100%;
}

.table th,
.table td {
  border: 1px solid var(--border);
  padding: 8px;
  text-align: left;
  vertical-align: top;
}

.list {
  margin: 0 0 1em;
  padding-inline-start: 1.35em;
}

.list li {
  margin: 0 0 0.4em;
}
`;

export function escapeText(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function escapeAttribute(value: string): string {
  return escapeText(value).replace(/"/g, "&quot;");
}

function indent(lines: string[], depth: number): string[] {
  const pad = "  ".repeat(depth);
  return lines.map((line) => pad + line);
}

function renderBlock(block: LegalBlock): string[] {
  switch (block.type) {
    case "paragraph":
      return [`<p class="paragraph">${escapeText(block.text)}</p>`];
    case "email":
      return [
        `<p class="paragraph">${escapeText(block.label)} <a class="link" href="mailto:${escapeAttribute(block.address)}">${escapeText(block.address)}</a></p>`,
      ];
    case "list":
      return [
        `<ul class="list">`,
        ...indent(
          block.items.map((item) => `<li>${escapeText(item)}</li>`),
          1
        ),
        `</ul>`,
      ];
    case "table":
      return [
        `<div class="table-scroll">`,
        `  <table class="table">`,
        `    <thead>`,
        `      <tr>`,
        ...indent(
          block.head.map((cell) => `<th scope="col">${escapeText(cell)}</th>`),
          4
        ),
        `      </tr>`,
        `    </thead>`,
        `    <tbody>`,
        ...block.rows.flatMap((row) => [
          `      <tr>`,
          ...indent(
            row.map((cell) => `<td>${escapeText(cell)}</td>`),
            4
          ),
          `      </tr>`,
        ]),
        `    </tbody>`,
        `  </table>`,
        `</div>`,
      ];
    default: {
      const unknown: never = block;
      throw new Error(`Unknown legal block: ${JSON.stringify(unknown)}`);
    }
  }
}

function renderDocument(doc: LegalDocument): string[] {
  return [
    `<main class="document">`,
    ...indent(
      [
        `<h1 class="title">${escapeText(doc.title)}</h1>`,
        `<p class="updated">${escapeText(doc.lastUpdated)}</p>`,
        ...doc.intro.flatMap(renderBlock),
        ...doc.sections.flatMap((section) => [
          `<section>`,
          ...indent(
            [
              `<h2 class="heading">${escapeText(section.heading)}</h2>`,
              ...section.blocks.flatMap(renderBlock),
            ],
            1
          ),
          `</section>`,
        ]),
      ],
      1
    ),
    `</main>`,
  ];
}

type Head = {
  title: string;
  description?: string;
  robots: "index, follow" | "noindex, nofollow";
  canonical?: string;
};

function renderPage(head: Head, main: string[]): string {
  const meta = [
    `<meta charset="utf-8">`,
    `<meta name="viewport" content="width=device-width, initial-scale=1">`,
    `<meta name="color-scheme" content="light dark">`,
    `<title>${escapeText(head.title)}</title>`,
    ...(head.description
      ? [`<meta name="description" content="${escapeAttribute(head.description)}">`]
      : []),
    `<meta name="robots" content="${head.robots}">`,
    ...(head.canonical
      ? [
          `<link rel="canonical" href="${escapeAttribute(head.canonical)}">`,
          `<meta property="og:type" content="website">`,
          `<meta property="og:title" content="${escapeAttribute(head.title)}">`,
          ...(head.description
            ? [`<meta property="og:description" content="${escapeAttribute(head.description)}">`]
            : []),
          `<meta property="og:url" content="${escapeAttribute(head.canonical)}">`,
        ]
      : []),
    // An empty icon, so browsers don't request /favicon.ico and log a 404.
    `<link rel="icon" href="data:,">`,
    `<style>`,
    ...STYLE.trimEnd().split("\n").map((line) => (line ? `  ${line}` : line)),
    `</style>`,
  ];

  return [
    "<!doctype html>",
    GENERATED_NOTE,
    `<html lang="en">`,
    `<head>`,
    ...indent(meta, 1).map((line) => line.trimEnd()),
    `</head>`,
    `<body>`,
    ...main,
    `</body>`,
    `</html>`,
    "",
  ].join("\n");
}

export function renderDocumentPage(page: DocumentPage): string {
  return renderPage(
    {
      title: page.doc.title,
      description: page.doc.description,
      robots: page.indexable ? "index, follow" : "noindex, nofollow",
      canonical: canonicalUrl(page.path),
    },
    renderDocument(page.doc)
  );
}

const INDEX_TITLE = "TrickTic legal documents";
const INDEX_DESCRIPTION =
  "Privacy policies, terms of use and security policies for apps published by TrickTic.";

/** Groups the listed documents by app, in registry order. */
export function indexListing(): { app: string; pages: DocumentPage[] }[] {
  const groups: { app: string; pages: DocumentPage[] }[] = [];
  for (const page of documentPages) {
    if (page.listedUnder === null) continue;
    let group = groups.find((entry) => entry.app === page.listedUnder);
    if (!group) {
      group = { app: page.listedUnder, pages: [] };
      groups.push(group);
    }
    group.pages.push(page);
  }
  return groups;
}

export function renderIndexPage(): string {
  return renderPage(
    {
      title: INDEX_TITLE,
      description: INDEX_DESCRIPTION,
      robots: "index, follow",
      canonical: `${SITE_ORIGIN}/`,
    },
    [
      `<main class="document">`,
      ...indent(
        [
          `<h1 class="title">${escapeText(INDEX_TITLE)}</h1>`,
          `<p class="paragraph">${escapeText(INDEX_DESCRIPTION)}</p>`,
          ...indexListing().flatMap(({ app, pages }) => [
            `<section>`,
            ...indent(
              [
                `<h2 class="heading">${escapeText(app)}</h2>`,
                `<ul class="list">`,
                ...indent(
                  pages.map(
                    (page) =>
                      `<li><a class="link" href="${escapeAttribute(page.path)}">${escapeText(page.doc.title)}</a></li>`
                  ),
                  1
                ),
                `</ul>`,
              ],
              1
            ),
            `</section>`,
          ]),
        ],
        1
      ),
      `</main>`,
    ]
  );
}

export function renderNotFoundPage(): string {
  return renderPage({ title: "Page not found", robots: "noindex, nofollow" }, [
    `<main class="document">`,
    `  <h1 class="title">Page not found</h1>`,
    `  <p class="paragraph">No TrickTic legal document lives at this address.</p>`,
    `  <p class="paragraph"><a class="link" href="/">See all TrickTic legal documents</a></p>`,
    `</main>`,
  ]);
}

/** Every file GitHub Pages serves, keyed by its path under docs/. */
export function siteFiles(): Map<string, string> {
  const files = new Map<string, string>();
  for (const page of documentPages) {
    const file = outputFile(page.path);
    if (files.has(file)) throw new Error(`Two documents claim ${page.path}`);
    files.set(file, renderDocumentPage(page));
  }
  files.set("index.html", renderIndexPage());
  files.set("404.html", renderNotFoundPage());
  files.set("CNAME", `${CNAME}\n`);
  // Serve docs/ as-is: no Jekyll processing.
  files.set(".nojekyll", "");
  return files;
}
